### ISSUE TITLE
Modbus support

### ISSUE THREAD

**Issue by marksev1** [mcbittech/souliss-smart-thermostat-WiFi#13]
Can you please add modbus support into this project?

**Comment by mcbittech** [comment]
Souliss support modbus, but only in AVR mcu.
There isn't modbus support on ESP now.
If you need modbus, i can suggest you to use a gateway Avr based and retrieve data from your SST, in order to have modbus support.

Flavio.

**Comment by marksev1** [comment]
Yeah thats not a good solution, to have redundant hardware just for that sole purpose. Hopefully you guys will provide also some other way to interact with esp outside of Souliss's internal protocols. Something widespread and easy to interact. Maybe this: https://github.com/souliss/souliss/issues/205 will be the solution. What do you think Flavio?

**Comment by mcbittech** [comment]
Why you need modbus?

Flavio.
Il 01/apr/2016 14:16, "marksev1" notifications@github.com ha scritto:

**Comment by marksev1** [comment]
I don't neccessary need modbus, I just need some protocol other than souliss's, some protocol which is  easier to interact with and which is more widespread. So I can build my custom dashboard and software around it.

**Comment by mcbittech** [comment]
SST is Souliss based :)
Se doesent plain external protocol.
You cannot build your dasboard around souliss?

Flavio.
Il 02/apr/2016 09:30, "marksev1" notifications@github.com ha scritto:
