### ISSUE TITLE
Topics Refresh in homepage with Layout 2

### ISSUE THREAD

**Issue by dariocdj** [mcbittech/souliss-smart-thermostat-WiFi#15]
In this moment topics refresh in layout 2 is not in realtime. It refresh every 50sec when slow50 refresh home screen. 
It would be better than refresh when getuichanged is true

**Comment by fazioa** [comment]
Now subscribe is in
 SHIFT_910ms(1)

It refresh only is data published are avaiable

**Comment by dariocdj** [comment]
Fantastic, tnx, also in layout 2 home?

**Comment by fazioa** [comment]
No. Only in dedicated topic page.
Il 2 giu 2016 4:55 PM, "Dario" notifications@github.com ha scritto:
