### ISSUE TITLE
child lock

### ISSUE THREAD

**Issue by fazioa** [mcbittech/souliss-smart-thermostat-WiFi#19]
Proposta: doppio click per inserire il blocco bambini, nuovamente doppio click per disinserito.
Il blocco bambini dovrebbe impedire di cambiare il Setpoint

**Comment by dariocdj** [comment]
+1

**Comment by fazioa** [comment]
Done

https://github.com/mcbittech/souliss-smart-thermostat-WiFi/commit/65a79166d2863b79006466aa379e8db51ddd56f0
