### ISSUE TITLE
Ora legale

### ISSUE THREAD

**Issue by dariocdj** [mcbittech/souliss-smart-thermostat-WiFi#23]
Prevedere flag ora legale. Con timezone 1 segna un ora prima....

**Comment by dariocdj** [comment]
Added DayLightSavingTime (ora legale) in getNtpTime function and in submenu "clock" but not considered when print time. Pheraps setSyncProvider(getNtpTime); doesn't work ?

**Comment by fazioa** [comment]
Fixed
https://github.com/mcbittech/souliss-smart-thermostat-WiFi/commit/36d52be59ecdbdf8b41ebeaef9e481f595d6ddfe
