### ISSUE TITLE
Layout Circular freeze when print circles

### ISSUE THREAD

**Issue by fazioa** [mcbittech/souliss-smart-thermostat-WiFi#26]

**Comment by mcbittech** [comment]
@fazioa can you explain better this issue?
Core ide etc...
With the released code i've never see this issue.

Il domenica 12 giugno 2016, fazioa notifications@github.com ha scritto:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/mcbittech/souliss-smart-thermostat-WiFi/issues/26,
> or mute the thread
> https://github.com/notifications/unsubscribe/AK-ONvjmT83zGRAuXQOVBYk-1Tjock28ks5qLGckgaJpZM4Iz3zB
> .

## 

P ********\* Consideriamo l'ambiente prima di stampare questa e-mail ***
Think about environment before printing *********
Il contenuto di questo messaggio e-mail è privato e riservato al solo
destinatario. L'utilizzo non autorizzato può costituire reato. Se ricevuto
erroneamente siete pregati di cancellarlo e comunicarci via e-mail l'errata
ricezione.

**Comment by mcbittech** [comment]
closed
