### ISSUE TITLE
Link non valido allo schema

### ISSUE THREAD

**Issue by dariocdj** [mcbittech/souliss-smart-thermostat-WiFi#3]
Ciao, 
https://github.com/mcbittech/souliss-smart-thermostat-WiFi/blob/master/SST_Connection.png?raw=true
non si vede più....
Mi sta arrivando il materiale....
grazie

Dario

**Comment by mcbittech** [comment]
Closed #3 with commit 544596e

**Comment by mcbittech** [comment]
Closed #3
https://github.com/mcbittech/souliss-smart-thermostat-WiFi/issues/3 with
commit 544596e
https://github.com/mcbittech/souliss-smart-thermostat-WiFi/commit/544596eebb0ce489a9f942bdad8f74ab6ae5b138

2015-12-27 21:49 GMT+01:00 Dario notifications@github.com:

> Ciao,
> 
> https://githubcom/mcbittech/souliss-smart-thermostat-WiFi/blob/master/SST_Connectionpng?raw=true
> non si vede più
> Mi sta arrivando il materiale
> grazie
> 
> Dario
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mcbittech/souliss-smart-thermostat-WiFi/issues/3.

## 

P ********\* Consideriamo l'ambiente prima di stampare questa e-mail ***
Think about environment before printing *********
Il contenuto di questo messaggio e-mail è privato e riservato al solo
destinatario. L'utilizzo non autorizzato può costituire reato. Se ricevuto
erroneamente siete pregati di cancellarlo e comunicarci via e-mail l'errata
ricezione.

**Comment by dariocdj** [comment]
grazie

On 27/12/2015 22:05, Flavio wrote:

> Closed #3 
> https://github.com/mcbittech/souliss-smart-thermostat-WiFi/issues/3.
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/mcbittech/souliss-smart-thermostat-WiFi/issues/3#event-500991249.
> 
> Nessun virus nel messaggio.
> Controllato da AVG - www.avg.com http://www.avg.com
> Versione: 2016.0.7294 / Database dei virus: 4489/11265 - Data di 
> rilascio: 27/12/2015

## 

---

```
                Dario ??Cdj??


  On Email: cdj@deskservice.com
  On Web  : http://www.cdj.deskservice.com
  On Irc  : Undernet.org #altraitalia
  On ICQ  : Uin # 3986985
  On MSN  : dariocdj@hotmail.it
  On Skype: dariocdj    

            Send me a fast reply !!!
```

---
