### ISSUE TITLE
Menù - asterisco

### ISSUE THREAD

**Issue by fazioa** [mcbittech/souliss-smart-thermostat-WiFi#41]
Sistemare comportamento menù

**Comment by dpeddi** [comment]
sto provando ad aggiornare al master di arduino-menusystem, dovrebbe semplificare la gestione della selezione

**Comment by fazioa** [comment]
Bene.
Attendiamo per i test.

Il gio 23 feb 2017, 17:41 dpeddi <notifications@github.com> ha scritto:

**Comment by dpeddi** [comment]
fatto a vecchio... mi pare proprio meglio

per la cronaca.... la versione sul git di arduino-menusystem prevede una sorta di slide... che sarebbe carina da implementare... 
in questo modo per selezionare la luminosità basterebbe un unica variabile
Current menu name: Level 1 - Item 3 (Menu)
Level 2 - Back (Item)
Level 2 - Item 1 (Item)
Level 2 - Txt Item 2 (Item)=Red
--|--------- 79.00
<<<


inoltre prevede dei componenti customizzabili che potrebbero essere comodi per il DTH offset
Level 1 - Float Item 4 (Item)<0.10><<<
Level 1 - Float Item 4 (Item)<1.00><<<






Current menu name: Level 1 - Item 3 (Menu)
Level 2 - Back (Item)
Level 2 - Item 1 (Item)
Level 2 - Txt Item 2 (Item)=Red
---|-------- 82.00

Però per come è gestito attualmente il display per limitare il refresh non è per niente banale passare alla versione nuova...

**Comment by fazioa** [comment]
Hai verificato che compili si esp?

**Comment by dpeddi** [comment]
La patch?

Si, compila e testata...

Funziona come previsto

Il 25/feb/2017 02:40 PM, "fazioa" <notifications@github.com> ha scritto:
