### ISSUE TITLE
Sospensione crono

### ISSUE THREAD

**Issue by fazioa** [mcbittech/souliss-smart-thermostat-WiFi#42]
Sospendere il crono per 30 minuti quando si imposta manualmente il setpoint

**Comment by mcbittech** [comment]
Non sono del tutto d'accordo.
In ogni caso se vuoi testarlo è molto semplice, basta triggerare la chiamata del crono ogni tempo che vuoi.
Se non ricordo male basta portare: 
      if (getCrono()) {
        Serial.println("CRONO: aggiornamento");
        setSetpoint(checkNTPcrono(ucg));
        setEncoderValue(checkNTPcrono(ucg));
        Serial.print("CRONO: setpoint: "); Serial.println(setpoint);
      }
che adesso è chiamata in una slow_50s, in una slow_xx che puoi configurare a piacimento.

**Comment by dariocdj** [comment]
Io lo farei per 2/3 ore... Mezz'ora manco te ne accorgi... Pop-up di conferma necessario
