### ISSUE TITLE
PCB disponibile?

### ISSUE THREAD

**Issue by katodo** [mcbittech/souliss-smart-thermostat-WiFi#53]
non so se è corretto aprire una issue anche per questo ma... esiste già un PCB di questo progetto? Volevo fare qualche prova ma odio le millefori e mi stavo per cimentare nel disegno ma se c'è qualcosa di pronto molto meglio :)

**Comment by mcbittech** [comment]
Ciao @katodo ,
no, non è corretto, comunque puoi trovare qui sul repo una versione da fresare qui:
https://github.com/mcbittech/souliss-smart-thermostat-WiFi/blob/master/Libraries-Core-Docs/Connection/PCB_layout.pdf
una versione da fotoincidere qui:
https://github.com/mcbittech/souliss-smart-thermostat-WiFi/blob/wbserver_beta/Libraries-Core-Docs/sst_pcb.fzz
una versione "industriale" qui:
 https://groups.google.com/d/msgid/souliss-it/bcdb9e0e-6643-496b-9813-10556e2531fb%40googlegroups.com
